### ISSUE TITLE
Network error on FreeNAS 10

### ISSUE THREAD

**Issue by mkaliyannan** [freenas/cli#5]
I freshly installed FreeNAS 10 beta on IBM server. and noticed network connection broken.

Follow the instructions as described on this doc:
1) set static ip and tried, no luck.
2) when I tried

```
 #network interface em0 up. 
 Task #8 error: Interface em0 is disabled. 
```

Network state was down. all the interfaces are same.
I can able to setup directly on the rc.conf and works well. however as described in doc, it won't  stay after reboot,

**Comment by 650elx** [comment]
Hi,

Have you tried to enable the interface ?

For example:
unix::/network/interface/em0>set enabled=yes

Regards

**Comment by 650elx** [comment]
Hi,

I'm closing this issue - If you have further problems please fill the ticket at bugs.freenas.org.
